version: "3"

services:
  lamp:
    image: alexcobra:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'some_password'
    command: /usr/sbin/apachectl -DFOREGROUND -k start
    volumes: 
      - /var/www/html:/var/www/html
      - /var/log/httpd:/var/log/httpd
      - mysqldb:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
    ports:
      - "80"
      - "443"
    networks:
      - backend
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
      - frontend
    
volumes:
  mysqldb:

networks:
  backend:
  frontend:
